version: '3.3'

services:   
   mongodb:
     image: mongo:$MONGO_VERSION
     container_name: $MONGO_CONTAINER_NAME
     ports:
      - 27017:27017
     environment:
       - MONGO_INITDB_ROOT_USERNAME=root
       - MONGO_INITDB_ROOT_PASSWORD=colav
       - MONGO_INTERNAL_NETWORK=true
       - MONGO_CONTAINER_NAME=mongodb
       - MONGO_CPUS=8
       - MONGO_RAM=12G
     ulimits:
      memlock:
        soft: -1
        hard: -1
     volumes:
      - mongodb_data:/data/db

     restart: always
     networks:
      - mongodb
     deploy:
            resources:
                limits:
                  cpus: $MONGO_CPUS
                  memory: $MONGO_RAM

networks:
  mongodb:
    driver: bridge
    internal: $MONGO_INTERNAL_NETWORK
volumes:
  mongodb_data: