version: '3.3'

services:   
   mongodb:
     image: mongo:$MONGO_VERSION
     container_name: mongodb
     command: [mongod]
     ports:
      - 27017:27017
     environment:
       if [ MONGO_SECURITY == "true" ]; then MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME fi
       if [ MONGO_SECURITY == "true" ]; then MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD fi     
     ulimits:
      memlock:
        soft: -1
        hard: -1
     volumes:
      - mongodb_data:/data/db

     restart: always
     networks:
      - mongodb
     deploy:
            resources:
                limits:
                  cpus: $MONGO_CPUS
                  memory: $MONGO_RAM

networks:
  mongodb:
    driver: bridge
    internal: true
volumes:
  mongodb_data: