version: '3.3'

services:   
   elastic_search:
     image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
     container_name: elasticsearch
     ports:
      - 9200:9200
      - 9300:9300
     environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_USERNAME=$ELASTIC_USERNAME
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
     ulimits:
      memlock:
        soft: -1
        hard: -1
     volumes:
      - es_data:/usr/share/elasticsearch/data

     restart: always
     networks:
      - elastic
     deploy:
            resources:
                limits:
                  cpus: '2.0'
                  memory: 4096M

networks:
  elastic:
    driver: bridge
    internal: true
volumes:
  es_data: